workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - flutter create myapp
      - cd myapp
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - myapp/build/app/outputs/flutter-apk/app-release.apk
